title: Anne Drake, LSCSW, LCSW, RPT - Counseling and Play Therapy

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
